spring.application.name=spring-boot-grpc

# default channel alternative configuration
spring.grpc.server.reflection.enabled=true
spring.grpc.server.health.enabled=true
spring.grpc.server.port=9090
spring.grpc.server.enabled=false

# named channel
spring.grpc.client.channel.local.target=static://localhost:9090
#spring.grpc.client.channel.local.target=0.0.0.0:9090

# actuator
management.endpoint.health.show-details=always
management.endpoints.web.exposure.include=*
management.server.port=9999

#logging.level.root=debug